Add support for rpi bullseye arm64; refactor to simplify
The rpi arm64 bullseye distribution is Debian with some extra Raspberry
packages, as opposed to the armhf {buster,bullseye} distributions which
are Raspbian.

Refactor to introduce the concept of "upstream" distribution, which
allows for common code across pc and rpi Debians.

diff --git a/build-rdir b/build-rdir
--- a/build-rdir
+++ b/build-rdir
@@ -18,10 +18,53 @@ if [ ${UID} != 0 ]; then
 fi
 
 # Common configuration
+extrainstall_norecommends=$(cat <<EOF
+postgresql-client
+openssh-client
+ntp
+acpid
+python3-psycopg2
+python3-reportlab
+python3-httplib2
+python3-qrcode
+python3-sqlalchemy
+python3-yaml
+quicktill-nfc-bridge
+oidentd
+usbutils
+pciutils
+python3-cups
+python3-odf
+telnet
+strace
+tcpdump
+python3-twython
+python3-oauthlib
+python3-requests
+python3-matplotlib
+wget
+man-db
+python3-dateutil
+python3-markupsafe
+quicktill-serial-barcode-bridge
+efibootmgr
+EOF
+			 )
 
-extrainstall_norecommends="postgresql-client openssh-client ntp acpid python3-psycopg2 python3-reportlab python3-httplib2 python3-qrcode python3-sqlalchemy python3-yaml quicktill-nfc-bridge oidentd usbutils pciutils python3-cups python3-odf telnet strace tcpdump python3-twython python3-oauthlib python3-requests python3-matplotlib wget man-db python3-dateutil"
-
-extrainstall_recommends="xinit python3-gi-cairo gir1.2-gtk-3.0 fonts-ubuntu fonts-symbola xterm matchbox-window-manager x11-xserver-utils python3-pil console-setup sntp"
+extrainstall_recommends=$(cat <<EOF
+xinit
+python3-gi-cairo
+gir1.2-gtk-3.0
+fonts-ubuntu
+fonts-symbola
+xterm
+matchbox-window-manager
+x11-xserver-utils
+python3-pil
+console-setup
+sntp
+EOF
+		       )
 
 # Address of tills apt repository, used during image creation to fetch
 # the quicktill-nfc-bridge package
@@ -31,37 +74,105 @@ repokey=keys/quicktill-repo.gpg.key
 # HTTP proxy to use as a cache; this should be configured to cache .deb files
 export http_proxy=http://sinister.sinister.greenend.org.uk:8000/
 
-# Platform-dependent configuration
+# Defaults
+function setup_pre_chroot { :; }
+function setup_post_chroot { :; }
 
-if [ "${platform}" = "pc" ]; then
-    extrainstall_norecommends="${extrainstall_norecommends} dmidecode"
-    case ${distribution} in
-	bionic|focal)
-	    source=http://gb.archive.ubuntu.com/ubuntu/
-	    debootstrap_keyring=
-	    boot=casper
-	    extrainstall_recommends="${extrainstall_recommends} xserver-xorg-hwe-18.04"
-	    function setup_pre_chroot {
-		cat >$target/etc/apt/sources.list <<EOF
+case ${platform} in
+    pc)
+	extrainstall_norecommends="${extrainstall_norecommends} dmidecode"
+	function setup_post_chroot {
+	    # For some reason the "lp" module is not loaded
+	    # automatically, so we have to add it to /etc/modules
+	    # here
+	    echo lp >>$target/etc/modules
+	}
+	case ${distribution} in
+	    bionic)
+		upstream=ubuntu
+		xserver=xserver-xorg-hwe-18.04
+		kernel=linux-generic-hwe-18.04
+		;;
+	    focal)
+		upstream=ubuntu
+		xserver=xserver-xorg
+		kernel=linux-generic-hwe-20.04
+		;;
+	    buster|bullseye)
+		upstream=debian
+		xserver=
+		case ${arch} in
+		    i386)
+			kernel=linux-image-686
+			;;
+		    amd64)
+			kernel=linux-image-amd64
+			;;
+		    *)
+			echo "Unknown pc arch ${arch}"
+			exit 1
+			;;
+		esac
+		;;
+	    *)
+		echo "Unknown pc distribution ${distribution}"
+		exit 1
+		;;
+	esac
+	extrainstall_recommends="${extrainstall_recommends} ${xserver}"
+	extrainstall_norecommends="${extrainstall_norecommends} ${kernel}"
+	;;
+    rpi)
+	case ${arch} in
+	    armhf)
+		upstream=raspbian
+		kernel="raspberrypi-kernel raspberrypi-bootloader"
+		;;
+	    arm64)
+		upstream=debian
+		kernel="raspberrypi-kernel raspberrypi-bootloader"
+		;;
+	    *)
+		echo "Unknown rpi arch ${arch}"
+		exit 1
+		;;
+	esac
+	extrainstall_norecommends="${extrainstall_norecommends} ${kernel}"
+	extrainstall_recommends="${extrainstall_recommends} libraspberrypi-bin"
+	function setup_pre_chroot {
+	    cat >>$target/etc/apt/sources.list <<EOF
+deb http://archive.raspberrypi.org/debian/ ${distribution} main
+EOF
+	    # Raspberry kernels and bootloaders are in a separate repo with its own key
+	    cp keys/raspberrypi.gpg.key $target/etc/apt/trusted.gpg.d/raspberrypi-key.asc
+	}
+	;;
+    *)
+	echo "Unknown platform ${platform}"
+	exit 1
+	;;
+esac
+
+case ${upstream} in
+    ubuntu)
+	source=http://gb.archive.ubuntu.com/ubuntu/
+	debootstrap_keyring=
+	boot=casper
+	function setup_apt_sources {
+	    cat >$target/etc/apt/sources.list <<EOF
 deb http://gb.archive.ubuntu.com/ubuntu $distribution main restricted universe multiverse
 deb http://gb.archive.ubuntu.com/ubuntu $distribution-updates main restricted universe multiverse
 deb http://security.ubuntu.com/ubuntu $distribution-security main restricted universe multiverse
 EOF
-	    }
-	    function setup_post_chroot {
-		# For some reason the "lp" module is not loaded
-		# automatically, so we have to add it to /etc/modules
-		# here
-		echo lp >>$target/etc/modules
-	    }
-	    ;;
-	buster|bullseye)
-	    source=http://deb.debian.org/debian/
-	    debootstrap_keyring=
-	    boot=live
-	    extrainstall_recommends="${extrainstall_recommends} sudo"
-	    function setup_pre_chroot {
-		cat >$target/etc/apt/sources.list <<EOF
+	}
+	;;
+    debian)
+	extrainstall_recommends="${extrainstall_recommends} sudo"
+	source=http://deb.debian.org/debian/
+	debootstrap_keyring=
+	boot=live
+	function setup_apt_sources {
+	    cat >$target/etc/apt/sources.list <<EOF
 deb http://deb.debian.org/debian/ $distribution main contrib non-free
 deb-src http://deb.debian.org/debian/ $distribution main contrib non-free
 
@@ -71,57 +182,23 @@ deb-src http://security.debian.org/debian-security $distribution/updates main co
 deb http://deb.debian.org/debian/ $distribution-updates main contrib non-free
 deb-src http://deb.debian.org/debian/ $distribution-updates main contrib non-free
 EOF
-	    }
-	    function setup_post_chroot {
-		# For some reason the "lp" module is not loaded
-		# automatically, so we have to add it to /etc/modules
-		# here
-		echo lp >>$target/etc/modules
-	    }
-	    ;;
-	*)
-	    echo "Unknown pc distribution ${distribution}"
-	    exit 1
-	    ;;
-    esac
-fi
-
-if [ "${platform}" = "rpi" ]; then
-    extrainstall_recommends="${extrainstall_recommends} libraspberrypi-bin sudo"
-    source=http://raspbian.raspberrypi.org/raspbian/
-    boot=live
-
-    echo Creating keyring using raspbian.public.key
-    rpi_keyring=$(tempfile --suffix=.gpg)
-    debootstrap_keyring="--keyring ${rpi_keyring}"
-    apt-key ${debootstrap_keyring} add keys/raspbian.public.key
-    function setup_pre_chroot {
-	cat >$target/etc/apt/sources.list <<EOF
+	}
+	;;
+    raspbian)
+	extrainstall_recommends="${extrainstall_recommends} sudo"
+	source=http://raspbian.raspberrypi.org/raspbian/
+	boot=live
+	echo Creating debootstrap keyring using raspbian.public.key
+	rpi_keyring=$(tempfile --suffix=.gpg)
+	debootstrap_keyring="--keyring ${rpi_keyring}"
+	apt-key ${debootstrap_keyring} add keys/raspbian.public.key
+	function setup_apt_sources {
+	    cat >$target/etc/apt/sources.list <<EOF
 deb http://raspbian.raspberrypi.org/raspbian/ ${distribution} main contrib non-free rpi
-deb http://archive.raspberrypi.org/debian/ ${distribution} main
 EOF
-	# Raspberry kernels and bootloaders are in a separate repo with its own key
-	cp keys/raspberrypi.gpg.key $target/etc/apt/trusted.gpg.d/raspberrypi-key.asc
-    }
-    function setup_post_chroot {
-	# Add a systemd-networkd config file
-	cat >$target/etc/systemd/network/till.network <<EOF
-[Match]
-Name=eth0
-Virtualization=false
-
-[Network]
-DHCP=true
-
-[DHCP]
-UseDNS=true
-EOF
-	# Prevent sudo from looking up the fqdn every time and failing
-	cat >$target/etc/sudoers.d/nolookup <<EOF
-Defaults !fqdn
-EOF
-    }
-fi
+	}
+	;;
+esac
 
 # Work out whether we are cross-building
 crossbuild=true
@@ -141,29 +218,13 @@ imginfo=${target}-image-info.yaml
 rm -rf $target $manifest $diskdefines $imginfo
 mkdir $target
 
-echo Running debootstrap
 if [ $crossbuild ]; then
+    echo Running qemu-debootstrap
     qemu-debootstrap ${debootstrap_keyring} --arch=${arch} $distribution $target $source 2>&1
-#    case "${arch}" in
-#	arm64)
-#	    cp /usr/bin/qemu-aarch64-static ${target}/usr/bin/
-#	    ;;
-#	armhf)
-#	    cp /usr/bin/qemu-arm-static ${target}/usr/bin/
-#	    ;;
-#	amd64|i386)
-#	    cp /usr/bin/qemu-i386-static ${target}/usr/bin/
-#	    ;;
-#    esac
 else
+    echo Running debootstrap
     debootstrap ${debootstrap_keyring} --arch=${arch} $distribution $target $source 2>&1
 fi
-
-# Seed the target with some useful files
-#cat >$target/etc/default/locale <<EOF
-#LANG="en_GB.UTF-8"
-#LANGUAGE="en_GB:en"
-#EOF
 
 # Use the http proxy if configured
 if [ "${http_proxy}" ]; then
@@ -175,8 +236,7 @@ fi
 # Override the default hostname
 echo till >$target/etc/hostname
 
-# Tills repository to fetch quicktill-nfc-bridge package (and other
-# till-related packages to be baked into the image)
+# Tills repository to fetch till-related packages to be baked into the image
 cat >$target/etc/apt/sources.list.d/till-boot.list <<EOF
 deb $repoaddr tills main
 EOF
@@ -187,15 +247,44 @@ cp -r scripts $target/root/
 echo $extrainstall_norecommends >$target/root/extrainstall_norecommends
 echo $extrainstall_recommends >$target/root/extrainstall_recommends
 
+cat >$target/root/chroot-config <<EOF
+platform=$platform
+arch=$arch
+EOF
+
 # Invoke the setup script in the target
+setup_apt_sources
 setup_pre_chroot
 rm -f $target/etc/resolv.conf
 systemd-nspawn -D $target/ -a /root/scripts/chroot-setup
 setup_post_chroot
 
+# Distribution-specific post-chroot functions
+case ${distribution} in
+    debian|raspbian)
+	# Add a systemd-networkd config file
+	cat >$target/etc/systemd/network/till.network <<EOF
+[Match]
+Name=eth0
+Virtualization=false
+
+[Network]
+DHCP=true
+
+[DHCP]
+UseDNS=true
+EOF
+	# Prevent sudo from looking up the fqdn every time and failing
+	cat >$target/etc/sudoers.d/nolookup <<EOF
+Defaults !fqdn
+EOF
+	;;
+esac
+
 # Clean up
 rm $target/root/extrainstall_norecommends
 rm $target/root/extrainstall_recommends
+rm $target/root/chroot-config
 rm -r $target/root/scripts
 
 # Clear the apt sources list
@@ -261,4 +350,9 @@ config-pi4:
 config:
   - dtoverlay=audio=on
 EOF
+    if [ "${arch}" = "arm64" ]; then
+	cat >>${imginfo} <<EOF
+  - arm_64bit=1
+EOF
+    fi
 fi
